hellostring: "Hello, worlda!"
pubSubTopic: robiTestingTopic
mqttAddress: tcp://localhost:1883
mqttUsername: robii
mqttPassword: masterPass

redisAddress: tcp://localhost:6379
kafkaAddress: tcp://localhost:9092
log4j:
  logger:
    org:
      hibernate: INFO